name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: pnpm install

      - name: Build Angular app
        run: pnpm ng build --configuration production --base-href "https://afhamsyahir.github.io/GitForNoob/"

      - name: Deploy to GitHub Pages
        run: pnpm exec angular-cli-ghpages --dir=dist/GitForNoob/browser --no-silent
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
